import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import App from "./App";
import {Toaster} from 'react-hot-toast';
import Navbar from "@/components/ui/navbar";
import {StoreProvider} from "./StoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gamerzz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>

          <div className="py-14">
            <Navbar />
            
            <Toaster position="bottom-center" reverseOrder={false} />
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
